--q7-
CREATE OR REPLACE PACKAGE MANAGE_BOOKS
AS
	PROCEDURE ADD_BOOK (i_book_id IN NUMBER, i_title IN VARCHAR2, i_category IN VARCHAR2, i_cost IN NUMBER);

	PROCEDURE REMOVE_BOOK (i_book_id IN NUMBER);

	PROCEDURE LIST_ALL_BOOKS(i_status IN VARCHAR2);

	PROCEDURE UPDATE_BOOK_STATUS (i_book_id IN NUMBER, i_status IN VARCHAR2);

	FUNCTION GET_BOOK_STATUS (i_book_id IN NUMBER) RETURN VARCHAR2;
END MANAGE_BOOKS;
/